### ISSUE TITLE
Admin would like to be able to set a custom message to broadcast

### ISSUE THREAD

**Issue by feardragon64** [tpavlek/laddertracker#4]
The admin would like the ability to broadcast a message to users at the top of every page.

Examples of this would be "Ladder Heroes is on hiatus and will return in December" or "The dates for ladder locks this month are December 5th, 12th 19th and 26th."

This feature should be a higher priority than this feature as it would act as a "temporary workaround":
https://github.com/tpavlek/laddertracker/issues/3

**Comment by tpavlek** [comment]
Resolved in latest.
